
server:
  port: 8084
spring:
    application:
        name: product-service
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: user
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate: 
           ddl-auto: update
        show-sql: true

eureka:
     client:
        service-url:
            defaultZone: http://localhost:8761/eureka/